apiVersion: v1
kind: Service
metadata:
  labels:
    app: integrationservice-app
    component: integrationservice
  name: integrationservice
spec:
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80 #8080
      # Port to forward to inside the pod
      #targetPort: 80
      # Port accessible outside cluster
      #nodePort: 30001
  selector:
    app: integrationservice-app
    component: integrationservice