version: '3.4'

services:
  backgroundworker:
    image: backgroundworker:dev
    build:
      target: base
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_backgroundworker$
    volumes:
      - C:\Users\fnikolovski.OFFICE\Downloads\BackgroundWorker\BackgroundWorker\BackgroundWorker:/app
      - C:\Users\fnikolovski.OFFICE\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_backgroundworker$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_backgroundworker$ \"bin/Debug/netcoreapp2.2/BackgroundWorker.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
